# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_book_name_with_image_custom_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import UI_files.resources.resources_rc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(215, 189)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("#Form{\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    border-radius: 50px;\n"
"}\n"
"\n"
"#widget{\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    padding: 10px, 10px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 30);\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 63 12pt \"Bahnschrift SemiBold SemiConden\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 5);\n"
"    color: rgb(200, 200, 200)\n"
"}\n"
"\n"
"#choose_book_btn{\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 63 10pt \"Bahnschrift SemiBold SemiConden\";\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.choose_book_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_book_btn.sizePolicy().hasHeightForWidth())
        self.choose_book_btn.setSizePolicy(sizePolicy)
        self.choose_book_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.choose_book_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/book-open-cover.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.choose_book_btn.setIcon(icon)
        self.choose_book_btn.setIconSize(QtCore.QSize(100, 100))
        self.choose_book_btn.setObjectName("choose_book_btn")
        self.verticalLayout.addWidget(self.choose_book_btn, 0, QtCore.Qt.AlignHCenter)
        self.label_for_book_name = QtWidgets.QLabel(self.widget)
        self.label_for_book_name.setObjectName("label_for_book_name")
        self.verticalLayout.addWidget(self.label_for_book_name, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.widget)
        self.del_btn = QtWidgets.QPushButton(Form)
        self.del_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_btn.setIcon(icon1)
        self.del_btn.setIconSize(QtCore.QSize(25, 25))
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout.addWidget(self.del_btn, 0, QtCore.Qt.AlignBottom)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_for_book_name.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">NAME</span></p></body></html>"))

