# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_exersize_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(390, 404)
        Form.setStyleSheet("#Form{\n"
"    background-color: rgb(50, 50, 50);\n"
"}\n"
"\n"
"QLabel, QPushButton{\n"
"    padding: 10px, 10px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 35);\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 63 12pt \"Bahnschrift SemiBold SemiConden\";\n"
"}\n"
"\n"
" QCheckBox{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 5px, 5px;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"\n"
"    \n"
"    background-color: rgba(255, 255, 255, 100);\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 63 12pt \"Bahnschrift SemiBold SemiConden\";\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_for_variants = QtWidgets.QVBoxLayout()
        self.verticalLayout_for_variants.setObjectName("verticalLayout_for_variants")
        self.verticalLayout_4.addLayout(self.verticalLayout_for_variants)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.next_btn = QtWidgets.QPushButton(self.widget_3)
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout.addWidget(self.next_btn)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Choose correct translation:"))
        self.next_btn.setText(_translate("Form", "Next"))
