# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_right_menu_current_book_page_custom_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(338, 509)
        Form.setStyleSheet("#widget{\n"
"    background-color: rgba(100, 100, 100, 100);\n"
"    \n"
"    border: none;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#word_btn{\n"
"    font: 63 12pt \"Bahnschrift SemiBold SemiConden\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding: 10px, 10px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 63 10pt \"Bahnschrift SemiBold SemiConden\";\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.word_btn = QtWidgets.QPushButton(self.widget)
        self.word_btn.setObjectName("word_btn")
        self.verticalLayout_2.addWidget(self.word_btn)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 320, 447))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(200, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_for_translations = QtWidgets.QVBoxLayout()
        self.verticalLayout_for_translations.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_for_translations.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_for_translations.setObjectName("verticalLayout_for_translations")
        self.verticalLayout_3.addLayout(self.verticalLayout_for_translations)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.word_btn.setText(_translate("Form", "WORD"))
