# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_word_and_translation_custom_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(282, 74)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("#widget{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(100, 100, 100, 50);\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding: 10px, 10px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 63 12pt \"Bahnschrift SemiBold SemiConden\";\n"
"}\n"
"\n"
"#language_btn{\n"
"    padding: 2px, 2px;\n"
"    padding-right: 4px;\n"
"    padding-left: 4px;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 63 10pt \"Bahnschrift SemiBold SemiConden\";\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_main = QtWidgets.QWidget(Form)
        self.widget_main.setObjectName("widget_main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_main)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.widget_main)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.word_btn = QtWidgets.QPushButton(self.widget_2)
        self.word_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_btn.sizePolicy().hasHeightForWidth())
        self.word_btn.setSizePolicy(sizePolicy)
        self.word_btn.setObjectName("word_btn")
        self.horizontalLayout.addWidget(self.word_btn)
        self.translation_btn = QtWidgets.QPushButton(self.widget_2)
        self.translation_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translation_btn.sizePolicy().hasHeightForWidth())
        self.translation_btn.setSizePolicy(sizePolicy)
        self.translation_btn.setObjectName("translation_btn")
        self.horizontalLayout.addWidget(self.translation_btn)
        self.horizontalLayout_4.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.language_btn = QtWidgets.QPushButton(self.widget_3)
        self.language_btn.setEnabled(False)
        self.language_btn.setObjectName("language_btn")
        self.horizontalLayout_3.addWidget(self.language_btn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.horizontalLayout_4.addWidget(self.widget_3)
        self.horizontalLayout_2.addWidget(self.widget)
        self.del_btn = QtWidgets.QPushButton(self.widget_main)
        self.del_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_btn.setIcon(icon)
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout_2.addWidget(self.del_btn)
        self.verticalLayout.addWidget(self.widget_main)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.word_btn.setText(_translate("Form", "word"))
        self.translation_btn.setText(_translate("Form", "translation"))
        self.language_btn.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.language_btn.setText(_translate("Form", "lang"))
